openapi: 3.0.0
info:
  title: Dream Tree API
  version: 1.0.0
tags:
  - name: auth
    description: User authentication
  - name: tree
    description: User tree management
  - name: dreams
    description: User dream management
  - name: user
    description: User profile management
  - name: follow
    description: User follow management

servers: # base endpoint
  - url: http://localhost:5000/api/v1
    description: base endpoint.

components:
  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT
  schemas:
    AuthResponse:
      type: object
      properties:
        token:
          type: string
          description: JWTトークン
        user_id:
          type: string
          description: ユーザID
      example:
        token: "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiIxMjM0NTY3ODkwIiwibmFtZSI6IuWxseeUsOWkqumDjiJ9"
        user_id: "123e4567-e89b-12d3-a456-426614174000"

paths:
  /auth/register:
    post:
      tags:
        - auth
      summary: 新しいユーザアカウントを登録する
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                username:
                  type: string
                  example: "山田太郎"
                email:
                  type: string
                  example: "user@example.com"
                password:
                  type: string
                  example: "password123"
      responses:
        201:
          description: User registered successfully
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/AuthResponse"

  /auth/login:
    post:
      tags:
        - auth
      summary: ユーザを認証してログインする
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                email:
                  type: string
                password:
                  type: string
      responses:
        200:
          description: User logged in successfully
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/AuthResponse"

  /auth/reset-password:
    post:
      tags:
        - auth
      summary: ユーザのメールにパスワードリセットリンクを送信する
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                email:
                  type: string
      responses:
        200:
          description: Password reset link sent successfully

  /users/{user_id}:
    get:
      tags:
        - user
      summary: ユーザプロフィールの詳細を取得する
      parameters:
        - name: user_id
          in: path
          required: true
          schema:
            type: string
      responses:
        200:
          description: User profile retrieved successfully
          content:
            application/json:
              schema:
                type: object
                properties:
                  id:
                    type: string
                    example: 2539df44-a215-4979-827c-7312e99391fa
                  name:
                    type: string
                    example: testuser
    patch:
      security:
        - bearerAuth: []
      tags:
        - user
      summary: ユーザプロフィール情報を更新する
      parameters:
        - name: user_id
          in: path
          required: true
          schema:
            type: string
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                email:
                  type: string
                  example: updated@example.com
                name:
                  type: string
                  example: updateduser
      responses:
        200:
          description: User profile updated successfully
          content:
            application/json:
              schema:
                type: object
                properties:
                  email:
                    type: string
                    example: updated@example.com
                  name:
                    type: string
                    example: updateuser

  /trees:
    get:
      tags:
        - tree
      summary: すべての木のリストを取得する
      responses:
        200:
          description: List of all trees retrieved successfully
          content:
            application/json:
              schema:
                type: array
                items:
                  type: object
                  properties:
                    id:
                      type: string
                      example: "123e4567-e89b-12d3-a456-426614174000"
                    user_id:
                      type: string
                      example: "123e4567-e89b-12d3-a456-426614174000"
                    title:
                      type: string
                      example: "プログラミングの夢"
                example:
                  - id: "123e4567-e89b-12d3-a456-426614174000"
                    title: "プログラミングの夢"
                    user_id: "123e4567-e89b-12d3-a456-426614174000"
                  - id: "987fcdeb-54ba-4321-8765-098765432100"
                    title: "起業への道"
                    user_id: "987fcdeb-54ba-4321-8765-098765432100"
                    

  /users/{user_id}/trees:
    get:
      tags:
        - tree
      summary: ユーザのすべての木のリストを取得する
      parameters:
        - name: user_id
          in: path
          required: true
          schema:
            type: string
      responses:
        200:
          description: List of all trees retrieved successfully
          content:
            application/json:
              schema:
                type: array
                items:
                  type: object
                  properties:
                    id:
                      type: string
                      example: "123e4567-e89b-12d3-a456-426614174000"
                    title:
                      type: string
                      example: "プログラミングの夢"
                example:
                  - id: "123e4567-e89b-12d3-a456-426614174000"
                    title: "プログラミングの夢"
                  - id: "987fcdeb-54ba-4321-8765-098765432100"
                    title: "起業への道"
    post:
      security:
        - bearerAuth: []
      tags:
        - tree
      summary: ユーザの新しい木を作成する
      parameters:
        - name: user_id
          in: path
          required: true
          schema:
            type: string
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                title:
                  type: string
                dreams:
                  type: array
                  items:
                    type: object
                    properties:
                      title:
                        type: string
                        example: "Webアプリケーションを作る"
                      position:
                        type: integer
                        example: 1
      responses:
        201:
          description: Tree created successfully
          content:
            application/json:
              schema:
                type: object
                properties:
                  id:
                    type: string
                    example: "123e4567-e89b-12d3-a456-426614174000"

  /users/{user_id}/trees/{tree_id}:
    get:
      tags:
        - tree
      summary: ユーザの木の詳細を取得する
      parameters:
        - name: user_id
          in: path
          required: true
          schema:
            type: string
        - name: tree_id
          in: path
          required: true
          schema:
            type: string
      responses:
        200:
          description: Tree retrieved successfully
          content:
            application/json:
              schema:
                type: object
                properties:
                  dreams:
                    type: array
                    items:
                      type: object
                      properties:
                        created_at:
                          type: string
                          example: "2024-01-01T00:00:00Z"
                        ended_at:
                          type: string
                          example: "2024-12-31T23:59:59Z"
                        id:
                          type: string
                          example: "456e7890-12cd-34ef-a456-426614174000"
                        position:
                          type: integer
                          example: 1
                        title:
                          type: string
                          example: "Webアプリケーションを作る"

    patch:
      security:
        - bearerAuth: []
      tags:
        - tree
      summary: ユーザの木の情報を更新する
      parameters:
        - name: user_id
          in: path
          required: true
          schema:
            type: string
        - name: tree_id
          in: path
          required: true
          schema:
            type: string
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                name:
                  type: string
                ended_at:
                  type: string
      responses:
        200:
          description: Tree updated successfully
          content:
            application/json:
              schema:
                type: object
                properties:
                  id:
                    type: string
                    example: eddef7ec-6392-4161-b361-1c555332107a
                  title:
                    type: string
                    example: Updated Programming Dream
            
    delete:
      security:
        - bearerAuth: []
      tags:
        - tree
      summary: ユーザの木を削除する（未実装）
      parameters:
        - name: user_id
          in: path
          required: true
          schema:
            type: string
        - name: tree_id
          in: path
          required: true
          schema:
            type: string
      responses:
        200:
          description: Tree deleted successfully

  /users/{user_id}/trees/{tree_id}/dreams:
    get:
      tags:
        - dreams
      summary: ユーザの木のすべての夢のリストを取得する（未実装?）
      parameters:
        - name: user_id
          in: path
          required: true
          schema:
            type: string
        - name: tree_id
          in: path
          required: true
          schema:
            type: string
      responses:
        200:
          description: List of all dreams retrieved successfully
          content:
            application/json:
              schema:
                type: array
                items:
                  type: object
                  properties:
                    id:
                      type: string
                      example: "456e7890-12cd-34ef-a456-426614174000"
                    title:
                      type: string
                      example: "Webアプリケーションを作る"
                    position:
                      type: integer
                      example: 1
                    created_at:
                      type: string
                      example: "2024-01-01T00:00:00Z"
                    ended_at:
                      type: string
                      example: "2024-12-31T23:59:59Z"
                example:
                  - id: "456e7890-12cd-34ef-a456-426614174000"
                    title: "Webアプリケーションを作る"
                    position: 1
                    created_at: "2024-01-01T00:00:00Z"
                    ended_at: "2024-12-31T23:59:59Z"
                  - id: "789f1234-56gh-78ij-b901-234567890123"
                    title: "スマートフォンアプリを作る"
                    position: 2
                    created_at: "2024-01-01T00:00:00Z"
                    ended_at: "2024-12-31T23:59:59Z"
    post:
      security:
        - bearerAuth: []
      tags:
        - dreams
      summary: ユーザの新しい夢を作成する（未実装?）
      parameters:
        - name: user_id
          in: path
          required: true
          schema:
            type: string
        - name: tree_id
          in: path
          required: true
          schema:
            type: string
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                title:
                  type: string
                position:
                  type: integer
      responses:
        201:
          description: Dream created successfully

  /users/{user_id}/trees/{tree_id}/dreams/{dream_id}:
    patch:
      security:
        - bearerAuth: []
      tags:
        - dreams
      summary: ユーザの夢の情報を更新する
      parameters:
        - name: user_id
          in: path
          required: true
          schema:
            type: string
        - name: tree_id
          in: path
          required: true
          schema:
            type: string
        - name: dream_id
          in: path
          required: true
          schema:
            type: string
      responses:
        200:
          description: Dream updated successfully
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
                    example: "success"

  /users:
    get:
      tags:
        - user
      summary: すべてのユーザプロフィールのリストを取得する
      responses:
        200:
          description: List of all user profiles retrieved successfully
          content:
            application/json:
              schema:
                type: array
                items:
                  type: object
                  properties:
                    email:
                      type: string
                      example: "yamada@example.com"
                    id:
                      type: string
                      example: "123e4567-e89b-12d3-a456-426614174000"
                    name:
                      type: string
                      example: "山田太郎"
                example:
                  - email: "yamada@example.com"
                    id: "123e4567-e89b-12d3-a456-426614174000"
                    name: "山田太郎"
                  - email: "suzuki@example.com"
                    id: "987fcdeb-54ba-4321-8765-098765432100"
                    name: "鈴木花子"

  /follow/{user_id}:
    post:
      security:
        - bearerAuth: []
      tags:
        - follow
      summary: ユーザをフォローする
      parameters:
        - name: user_id
          in: path
          required: true
          schema:
            type: string
      responses:
        201:
          description: Follow created successfully
          content:
            application/json:
              schema:
                type: object
                properties:
                  from_user_id:
                    type: string
                    example: eddef7ec-6392-4161-b361-1c555332107a
                  to_user_id:
                    type: string
                    example: 123e4567-e89b-12d3-a456-426614174000
    delete:
      security:
        - bearerAuth: []
      tags:
        - follow
      summary: ユーザのフォローを解除する
      parameters:
        - name: user_id
          in: path
          required: true
          schema:
            type: string
      responses:
        200:
          description: Follow deleted successfully
          content:
            application/json:
              schema:
                type: object
                properties:
                  from_user_id:
                    type: string
                    example: eddef7ec-6392-4161-b361-1c555332107a
                  to_user_id:
                    type: string
                    example: 123e4567-e89b-12d3-a456-426614174000
                    
  /follow/{user_id}/followers:
    get:
      tags:
        - follow
      summary: ユーザのことをフォローしているユーザのリストを取得する
      parameters:
        - name: user_id
          in: path
          required: true
          schema:
            type: string
      responses:
        200:
          description: List of followers retrieved successfully
          content:
            application/json:
              schema:
                type: array
                items:
                  type: object
                  properties:
                    id:
                      type: string
                      example: "123e4567-e89b-12d3-a456-426614174000"
                    name:
                      type: string
                      example: "田中次郎"
                example:
                  - id: "123e4567-e89b-12d3-a456-426614174000"
                    name: "田中次郎"
                  - id: "987fcdeb-54ba-4321-8765-098765432100"
                    name: "佐藤花子"

  /follow/{user_id}/following:
    get:
      tags:
        - follow
      summary: ユーザがフォローしているユーザのリストを取得する
      parameters:
        - name: user_id
          in: path
          required: true
          schema:
            type: string
      responses:
        200:
          description: List of following retrieved successfully
          content:
            application/json:
              schema:
                type: array
                items:
                  type: object
                  properties:
                    id:
                      type: string
                      example: "123e4567-e89b-12d3-a456-426614174000"
                    name:
                      type: string
                      example: "佐藤次郎"
                example:
                  - id: "123e4567-e89b-12d3-a456-426614174000"
                    name: "佐藤次郎"
                  - id: "987fcdeb-54ba-4321-8765-098765432100"
                    name: "田中花子"
